CREATE TABLE IF NOT EXISTS PERSON (
  ID INT IDENTITY PRIMARY KEY,
  NAME VARCHAR(50),
  FIRSTNAME VARCHAR(50),
  AGE INT,
  WEARSGLASSES VARCHAR(1)
);

INSERT INTO PERSON (NAME, FIRSTNAME, AGE, WEARSGLASSES) values
('A', 'B', 5, '1'),
('B', 'C', 6, '0'),
('C', 'D', 5, '1');